# ============================
# LAPTOP STARTUP
# ============================

# Gnome keyring
# Only needed if not already started by the system/session
exec-once = hypridle -c ~/.config/hypr/services/laptop/hypridle.conf
exec-once = /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg && export $(/usr/bin/gnome-keyring-daemon --start)
exec-once = awww-daemon
exec-once = sleep 1 && awww img $HOME/Pictures/Homescreen/Homescreen.png