# ============================
# SHARED STARTUP
# ============================

# Wallpaper daemon
exec-once = swww-daemon

# Static wallpaper (temporary until rotation script is fixed)

exec-once = waybar -c ~/.config/hypr/services/shared/waybar/config.jsonc -s ~/.config/hypr/services/shared/waybar/style.css