# ============================
# PC ONLY KEYBINDS
# ============================

# TODO:
# Add PC-specific shortcuts here


# Example:
# OpenRGB
bind = $mainMod SHIFT, O, exec, sh -c 'pkill openrgb; openrgb --server; sleep 1; openrgb -p newred'