# ============================
# HYPRLAND MAIN CONFIG
# ============================

# Core
source = ~/.config/hypr/core/variables.conf
source = ~/.config/hypr/core/environment.conf
source = ~/.config/hypr/core/input.conf
exec-once = swww img $HOME/Pictures/Homescreen/Homescreen.png`


# Machine
source = ~/.config/hypr/machines/laptop.conf
# source = ~/.config/hypr/machines/pc.conf


# UI
source = ~/.config/hypr/ui/animations.conf
source = ~/.config/hypr/ui/decorations.conf


# Keybinds
source = ~/.config/hypr/keybinds/shared.conf

# Startup
source = ~/.config/hypr/startup/shared.conf