# ============================
# PC MONITOR CONFIG
# ============================

# TODO:
# Add PC-specific monitor layout here
# Example:
# monitor=DP-1,2560x1440@165,0x0,1
# monitor=HDMI-A-1,1920x1200@60,2560x0,1

monitor=,preferred,auto,auto