# ============================
# LAPTOP MACHINE PROFILE
# ============================


# Monitor setup
source = ~/.config/hypr/monitors/laptop.conf


# Laptop specific keybinds
source = ~/.config/hypr/keybinds/laptop/special.conf


# Laptop rules
source = ~/.config/hypr/rules/laptop.conf


# Laptop startup
source = ~/.config/hypr/startup/laptop.conf