# ============================
# PC MACHINE PROFILE
# ============================


# Monitor setup
source = ~/.config/hypr/monitors/pc.conf


# PC specific keybinds
source = ~/.config/hypr/keybinds/pc/special.conf


# PC rules
source = ~/.config/hypr/rules/pc.conf


# PC startup
source = ~/.config/hypr/scripts/pc/startup.conf