# ============================
# PC STARTUP
# ============================

# Eww
exec-once = eww daemon
exec-once = sleep 1 && eww open background_clock

# OpenRGB
exec-once = pkill openrgb
exec-once = openrgb --server
exec-once = sleep 2 && openrgb -p newred