# ============================
# INPUT CONFIGURATION
# ============================


input {

    # Keyboard layout

    kb_layout = us

    kb_variant =
    kb_model =
    kb_options =
    kb_rules =


    # Mouse

    follow_mouse = 1

    sensitivity = 0


    # Touchpad

    touchpad {

        natural_scroll = false
    }
}



# ============================
# GESTURES
# ============================

gesture = 3, horizontal, workspace



# ============================
# DEVICE OVERRIDES
# ============================

# Example:
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
# }