# ============================
# HYPRLAND VARIABLES
# ============================


# Modifier key
$mainMod = SUPER


# Applications

$terminal = kitty

$fileManager = dolphin

$browser = vivaldi

$menu = wofi --show drun


# Optional:
# Add more later when needed
#
# $systemMonitor = mate-system-monitor
# $launcher = wofi --show drun